services:
  database:
    image: 'postgres:latest'
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - .docker/db/data/:/var/lib/postgresql/data/
      - .docker/db/init.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-root}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-root} -d ${DB_NAME:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  clementine:
    depends_on:
      - database
    image: chainwayxyz/clementine:testnet
    platform: linux/amd64
    container_name: full-node
    environment:
      - RUST_LOG=trace
    ports:
      - "8080:8080"
    volumes:
      - clementine:/mnt/task/clementine-db
    networks:
      - clementine-testnet-network

volumes:
  database:
  clementine:

networks:
  clementine-testnet-network:
    driver: bridge
