name: Clementine Operator Full Stack

services:
  postgres_db:
    image: 'postgres:latest'
    attach: false
    container_name: postgres_db
    volumes:
      - .docker/db/data/:/var/lib/postgresql/data/
      - .docker/db/init.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: clementine
      POSTGRES_PASSWORD: clementine
      POSTGRES_DB: clementine
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clementine -d clementine"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - clementine-network

  bitcoin_regtest:
    image: bitcoin/bitcoin:29
    attach: false
    container_name: bitcoin_regtest
    ports:
      - "20443:20443"
      - "20444:20444"
    command:
      -printtoconsole
      -regtest=1
      -rest
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcport=20443
      -rpcuser=admin
      -rpcpassword=admin
      -server
      -txindex=1
      -fallbackfee=0.00001
      -maxtxfee=5
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=20443 loadwallet admin || bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=20443 createwallet admin; bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=20443 -rpcwallet=admin generatetoaddress 202 $(bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=20443 -rpcwallet=admin getnewaddress); bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=20443 getblockchaininfo"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - bitcoin_regtest:/home/bitcoin/.bitcoin
    networks:
      - clementine-network

  citrea_sequencer:
    image: chainwayxyz/citrea
    attach: false
    depends_on:
      bitcoin_regtest:
        condition: service_healthy
    container_name: citrea_sequencer
    command:
      --dev --da-layer bitcoin --rollup-config-path /sequencer_rollup_config.toml --sequencer /sequencer_config.toml --genesis-paths /genesis-bitcoin-regtest/
    ports:
      - "12345:8080"
    volumes:
      - ./configs/citrea/sequencer_rollup_config.toml:/sequencer_rollup_config.toml
      - ./configs/citrea/sequencer_config.toml:/sequencer_config.toml
      - ./configs/citrea/genesis-bitcoin-regtest:/genesis-bitcoin-regtest
    networks:
      - clementine-network

  citrea_full_node:
    image: chainwayxyz/citrea
    attach: false
    depends_on:
      bitcoin_regtest:
        condition: service_healthy
      citrea_sequencer:
        condition: service_started
    container_name: citrea_full_node
    command:
      --dev --da-layer bitcoin --rollup-config-path /rollup_config.toml --genesis-paths resources/genesis/bitcoin-regtest/
    ports:
      - "12346:8080"
    volumes:
      - ./configs/citrea/rollup_config.toml:/rollup_config.toml
      - ./configs/citrea/genesis-bitcoin-regtest:/genesis-bitcoin-regtest
    networks:
      - clementine-network

  citrea_batch_prover:
    image: chainwayxyz/citrea
    attach: false
    depends_on:
      bitcoin_regtest:
        condition: service_healthy
      citrea_sequencer:
        condition: service_started
      citrea_full_node:
        condition: service_started
    container_name: citrea_batch_prover
    command:
      --dev --da-layer bitcoin --rollup-config-path /batch_prover_rollup_config.toml --batch-prover /batch_prover_config.toml --genesis-paths /bitcoin-regtest
    ports:
      - "12347:8080"
    volumes:
      - ./configs/citrea/batch_prover_rollup_config.toml:/batch_prover_rollup_config.toml
      - ./configs/citrea/batch_prover_config.toml:/batch_prover_config.toml
      - ./configs/citrea/genesis-bitcoin-regtest:/genesis-bitcoin-regtest
    networks:
      - clementine-network

  citrea_light_client_prover:
    image: chainwayxyz/citrea
    attach: false
    depends_on:
      bitcoin_regtest:
        condition: service_healthy
      citrea_sequencer:
        condition: service_started
      citrea_full_node:
        condition: service_started
      citrea_batch_prover:
        condition: service_started
    container_name: citrea_light_client_prover
    command:
      --dev --da-layer bitcoin --rollup-config-path /light_client_prover_rollup_config.toml --light-client-prover /light_client_prover_config.toml --genesis-paths /bitcoin-regtest
    ports:
      - "12348:8080"
    volumes:
      - ./configs/citrea/light_client_prover_rollup_config.toml:/light_client_prover_rollup_config.toml
      - ./configs/citrea/light_client_prover_config.toml:/light_client_prover_config.toml
      - ./configs/citrea/genesis-bitcoin-regtest:/genesis-bitcoin-regtest
    networks:
      - clementine-network

  clementine_verifier:
    depends_on:
      postgres_db:
        condition: service_healthy
      bitcoin_regtest:
        condition: service_healthy
      citrea_sequencer:
        condition: service_started
      citrea_full_node:
        condition: service_started
      citrea_batch_prover:
        condition: service_started
      citrea_light_client_prover:
        condition: service_started
    image: chainwayxyz/clementine
    platform: linux/amd64
    container_name: clementine_verifier
    environment:
      - BITVM_CACHE_PATH=/bitvm_cache.bin
    command:
      verifier --config /config.toml --protocol-params /protocol_paramset.toml
    ports:
      - "9080:8080"
    volumes:
      - ./configs/docker_config.toml:/config.toml
      - ./configs/docker_protocol_paramset.toml:/protocol_paramset.toml
      - ../../bitvm_cache.bin:/bitvm_cache.bin
      - ../../core/certs:/certs
    networks:
      - clementine-network

  clementine_operator:
    depends_on:
      postgres_db:
        condition: service_healthy
      bitcoin_regtest:
        condition: service_healthy
      clementine_verifier:
        condition: service_started
      citrea_sequencer:
        condition: service_started
      citrea_full_node:
        condition: service_started
      citrea_batch_prover:
        condition: service_started
      citrea_light_client_prover:
        condition: service_started
    image: chainwayxyz/clementine
    platform: linux/amd64
    container_name: clementine_operator
    environment:
      - BITVM_CACHE_PATH=/bitvm_cache.bin
    command:
      operator --config /config.toml --protocol-params /protocol_paramset.toml
    ports:
      - "7080:8080"
    volumes:
      - ./configs/docker_config.toml:/config.toml
      - ./configs/docker_protocol_paramset.toml:/protocol_paramset.toml
      - ../../bitvm_cache.bin:/bitvm_cache.bin
      - ../../core/certs:/certs
    networks:
      - clementine-network

volumes:
  postgres_db:
  bitcoin_regtest:
  clementine_verifier:
  clementine_operator:

networks:
  clementine-network:
    driver: bridge
