name: Clementine Verifier and Operator

services:
  postgres_db:
    image: 'postgres:latest'
    attach: false
    container_name: postgres_db
    volumes:
      - .docker/db/data/:/var/lib/postgresql/data/
      - .docker/db/init.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: clementine
      POSTGRES_PASSWORD: clementine
      POSTGRES_DB: clementine
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clementine -d clementine"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - clementine-network

  bitcoin_regtest:
    image: bitcoin/bitcoin:29
    # attach: false
    container_name: bitcoin_regtest
    ports:
      - "19443:19443"
      - "19444:19444"
    command:
      -printtoconsole
      -regtest=1
      -rest
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcport=19443
      -rpcuser=admin
      -rpcpassword=admin
      -server
      -txindex=1
      -fallbackfee=0.00001
      -maxtxfee=5
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=19443 loadwallet admin || bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=19443 createwallet admin; bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=19443 -rpcwallet=admin generatetoaddress 101 $(bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=19443 -rpcwallet=admin getnewaddress); bitcoin-cli -regtest -rpcuser=admin -rpcpassword=admin -rpcport=19443 getblockchaininfo"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - bitcoin_regtest:/home/bitcoin/.bitcoin
    networks:
      - clementine-network

  clementine_verifier:
    depends_on:
      postgres_db:
        condition: service_healthy
      bitcoin_regtest:
        condition: service_healthy
    image: chainwayxyz/clementine
    platform: linux/amd64
    container_name: clementine
    environment:
      - BITVM_CACHE_PATH=/bitvm_cache.bin
    command:
      verifier --config /config.toml --protocol-params /protocol_paramset.toml
    ports:
      - "9080:8080"
    volumes:
      - ./docker_config.toml:/config.toml
      - ../../core/src/test/data/protocol_paramset.toml:/protocol_paramset.toml
      - ../../bitvm_cache.bin:/bitvm_cache.bin
      - ../../core/certs:/certs

    networks:
      - clementine-network

  clementine_operator:
    depends_on:
      postgres_db:
        condition: service_healthy
      bitcoin_regtest:
        condition: service_healthy
      clementine_verifier:
        condition: service_started
    image: chainwayxyz/clementine
    platform: linux/amd64
    container_name: clementine-operator
    environment:
      - BITVM_CACHE_PATH=/bitvm_cache.bin
    command:
      operator --config /config.toml --protocol-params /protocol_paramset.toml
    ports:
      - "7080:8080"
    volumes:
      - ./docker_config.toml:/config.toml
      - ../../core/src/test/data/protocol_paramset.toml:/protocol_paramset.toml
      - ../../bitvm_cache.bin:/bitvm_cache.bin
      - ../../core/certs:/certs

    networks:
      - clementine-network

volumes:
  postgres_db:
  bitcoin_regtest:
  clementine_verifier:
  clementine_operator:

networks:
  clementine-network:
    driver: bridge
