services:
  postgres_db:
    image: 'postgres:latest'
    container_name: postgres_db
    volumes:
      - .docker/db/data/:/var/lib/postgresql/data/
      - .docker/db/init.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: clementine
      POSTGRES_PASSWORD: clementine
      POSTGRES_DB: clementine
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clementine -d clementine"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - clementine-network

  bitcoin_testnet4:
    image: bitcoin/bitcoin:28.1
    container_name: bitcoin_testnet4
    ports:
      - "18443:18443"
      - "18444:18444"
    command:
      -printtoconsole
      -testnet4=1
      -rest
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcport=18443
      -rpcuser=admin
      -rpcpassword=admin
      -server
      -txindex=1
    volumes:
      - bitcoin_testnet4:/home/bitcoin/.bitcoin
    networks:
      - clementine-network

  clementine:
    depends_on:
      - postgres_db
      - bitcoin_testnet4
    image: clementine
    platform: linux/amd64
    container_name: clementine
    command:
      /scripts/docker/docker_config.toml
      --verifier-server
    environment:
      - RUST_LOG=info
    ports:
      - "8080:8080"
    volumes:
      - clementine:/mnt/task/clementine
    networks:
      - clementine-network

volumes:
  postgres_db:
  bitcoin_testnet4:
  clementine:

networks:
  clementine-network:
    driver: bridge
