name: Clementine Verifier and Operator Services Without Bitcoin Node

services:
  postgres_db:
    image: 'postgres:latest'
    attach: false
    container_name: postgres_db
    volumes:
      - .docker/db/data/:/var/lib/postgresql/data/
      - .docker/db/init.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: clementine
      POSTGRES_PASSWORD: clementine
      POSTGRES_DB: clementine
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clementine -d clementine"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - clementine-network

  clementine_verifier:
    depends_on:
      postgres_db:
        condition: service_healthy
    image: chainwayxyz/clementine
    platform: linux/amd64
    container_name: clementine_verifier
    environment:
      - BITVM_CACHE_PATH=/bitvm_cache.bin
    command:
      verifier --config /config.toml --protocol-params /protocol_paramset.toml
    ports:
      - "9080:8080"
    volumes:
      - ./docker_config.toml:/config.toml
      - ./docker_protocol_paramset.toml:/protocol_paramset.toml
      - ../../bitvm_cache.bin:/bitvm_cache.bin
      - ../../core/certs:/certs

    networks:
      - clementine-network

  clementine_operator:
    depends_on:
      postgres_db:
        condition: service_healthy
      clementine_verifier:
        condition: service_started
    image: chainwayxyz/clementine
    platform: linux/amd64
    container_name: clementine_operator
    environment:
      - BITVM_CACHE_PATH=/bitvm_cache.bin
    command:
      operator --config /config.toml --protocol-params /protocol_paramset.toml
    ports:
      - "7080:8080"
    volumes:
      - ./docker_config.toml:/config.toml
      - ./docker_protocol_paramset.toml:/protocol_paramset.toml
      - ../../bitvm_cache.bin:/bitvm_cache.bin
      - ../../core/certs:/certs

    networks:
      - clementine-network

volumes:
  postgres_db:
  clementine_verifier:
  clementine_operator:

networks:
  clementine-network:
    driver: bridge
