[package]
name = "bridge-circuit"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { version = "2.1.2", features = ["unstable"] }
risc0-binfmt = {version = "2.0.1"}

[package.metadata.risc0]
methods = ["guest"]