name: Bug Template
description: This issue template is used for bug reports.
assignees: []
labels: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following sections to help us reproduce and fix the bug.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      placeholder: "Explain what should happen"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      placeholder: "Explain what happens instead of the expected behavior"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: "Provide an unambiguous set of steps to reproduce the bug"
    validations:
      required: true

  - type: textarea
    id: possible-solutions
    attributes:
      label: Possible Solutions or Workarounds
      placeholder: "Optional solution or workaround suggestions"

  - type: textarea
    id: notes
    attributes:
      label: Notes
      placeholder: "Optional final notes"
