# Start required services for testing Clementine.

name: Clementine Test Services
description: "Start services required for testing Clementine"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"

  steps:
    - name: Download bitvm cache bin
      shell: bash
      run: wget https://static.testnet.citrea.xyz/common/bitvm_cache_v3.bin -O core/bitvm_cache.bin
    - name: Download bitvm cache dev bin
      shell: bash
      run: wget https://static.testnet.citrea.xyz/common/bitvm_cache_dev.bin -O core/bitvm_cache_dev.bin
    - name: Download Bitcoin
      shell: bash
      run: wget https://bitcoincore.org/bin/bitcoin-core-29.0/bitcoin-29.0-x86_64-linux-gnu.tar.gz
    - name: Unpack Bitcoin
      shell: bash
      run: tar -xzvf bitcoin-29.0-x86_64-linux-gnu.tar.gz

    - name: Set executable permissions
      shell: bash
      run: chmod +x bitcoin-29.0/bin/*

    - name: Add bitcoin to path
      shell: bash
      run: echo "$PWD/bitcoin-29.0/bin" >> $GITHUB_PATH