[package]
name = "header-chain"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { version = "3.0.3", features = ["unstable"] }
risc0-binfmt = {version = "3.0.2"}

[package.metadata.risc0]
methods = ["guest"]