[package]
name = "header-chain"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "2.1.0", features = ["unstable"] }
risc0-binfmt = {version = "2.0.0"}

[package.metadata.risc0]
methods = ["guest"]
