# Start required services for building Clementine.

name: Clementine Build Services
description: 'Start services required for building Clementine'

runs:
  using: "composite"

  steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
      with:
        repo-token: ${{ github.token }}
