use std::{fs::File, io::BufReader};

// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use bridge_core::{btc::BlockHeader, config::N, incremental_merkle::IncrementalMerkleTree};
use bridge_methods::{GUEST_ELF, GUEST_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use serde_json::Value;

#[allow(non_snake_case)]
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct BlockInfoExtras {
    reward: u128,
    coinbaseRaw: String,
    orphans: Vec<String>,
    medianFee: f64,
    feeRange: Vec<f64>,
    coinbaseAddress: String,
    header: String,
    // ...
    // add the fields you want
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct BlockInfo {
    id: String,
    height: usize,
    version: usize,
    timestamp: u128,
    bits: u128,
    nonce: u128,
    difficulty: f64,
    merkle_root: String,
    tx_count: usize,
    size: u128,
    weight: u128,
    previousblockhash: String,
    mediantime: u128,
    stale: bool,
    extras: BlockInfoExtras,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct RpcResult {
    bestblockhash: String,
    chainwork: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct RpcInfo {
    result: RpcResult,
}

pub fn json_to_obj<T: DeserializeOwned>(file_path: &str) -> T {
    let file = File::open(file_path).expect("error");
    let reader = BufReader::new(file);
    let a: T = serde_json::from_reader(reader).expect("error");
    return a;
}

fn main() {
    env_logger::init();

    let deposit_merkle_tree = IncrementalMerkleTree::initial();
    let withdrawal_merkle_tree = IncrementalMerkleTree::initial();
    let bridge_funds_merkle_tree = IncrementalMerkleTree::initial();

    let block_info_list: Vec<BlockInfo> = json_to_obj::<Value>("./circuits/host/data/block.json")
        .as_array()
        .unwrap()
        .iter()
        .map(|block_info_value| {
            serde_json::from_value::<BlockInfo>(block_info_value.clone()).unwrap()
        })
        .collect();

    let rpc_info_list: Vec<RpcInfo> = json_to_obj::<Value>("./circuits/host/data/rpc.json")
        .as_array()
        .unwrap()
        .iter()
        .map(|rpc_info_value| serde_json::from_value::<RpcInfo>(rpc_info_value.clone()).unwrap())
        .collect();

    // assert_eq!(rpc_info_list.len() - block_info_list.len(), 1);

    let first_chain_work: [u8; 32] = hex::decode(rpc_info_list[0].result.chainwork.clone())
        .unwrap()
        .try_into()
        .unwrap();

    let initial_block_hash: [u8; 32] = hex::decode(block_info_list[0].previousblockhash.clone())
        .unwrap()
        .try_into()
        .unwrap();

    let mut env = ExecutorEnv::builder();

    env.write(&deposit_merkle_tree.index).unwrap();
    env.write(&withdrawal_merkle_tree.index).unwrap();
    env.write(&initial_block_hash).unwrap();
    env.write(&first_chain_work).unwrap();
    env.write(&bridge_funds_merkle_tree.root).unwrap();

    env.write(&deposit_merkle_tree).unwrap();
    env.write(&withdrawal_merkle_tree).unwrap();
    env.write(&bridge_funds_merkle_tree).unwrap();

    env.write(&3).unwrap();  // number of txids
    env.write(&[7_u8; 32]).unwrap();
    env.write(&[5_u8; 32]).unwrap();
    env.write(&[3_u8; 32]).unwrap();

    env.write(&0).unwrap();  // last_unspent_bridge_fund_index

    for i in 0..N as usize {
        let block_header: [u8; 80] = hex::decode(block_info_list[i].extras.header.clone())
            .unwrap()
            .try_into()
            .unwrap();
        let block_header = BlockHeader::from_slice(&block_header);
        env.write(&block_header).unwrap();

        env.write(&0).unwrap();  // number of withdrawals
        env.write(&0).unwrap();  // number of deposits
    }

    let env_build = env.build().unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Produce a receipt by proving the specified ELF binary.
    let receipt = prover.prove_elf(env_build, GUEST_ELF).unwrap();

    let (mut start_deposit_index, start_withdrawal_index, initial_block_hash, initial_work, initial_bridge_funds_merkle_root, deposit_last_index, withdrawal_last_index, mut output_block_hash, light_client_pow, bridge_funds_merkle_root, mut last_finalized_block_hash, last_chain_work): (u32, u32, [u8; 32], [u8; 32], [u8; 32], u32, u32, [u8; 32], [u8; 32], [u8; 32], [u8; 32], [u8; 32]) =
        receipt.journal.decode().unwrap();

    output_block_hash.reverse();
    last_finalized_block_hash.reverse();

    println!("Output: {}", hex::encode(output_block_hash));
    println!("Output: {}", hex::encode(last_finalized_block_hash));
    println!("Chain Work: {}", hex::encode(last_chain_work));

    assert_eq!(
        hex::encode(last_chain_work),
        rpc_info_list[rpc_info_list.len() - 1].result.chainwork
    );

    assert_eq!(
        hex::encode(last_finalized_block_hash),
        rpc_info_list[rpc_info_list.len() - 1].result.bestblockhash
    );

    // Optional: Verify receipt to confirm that recipients will also be able to
    // verify your receipt
    receipt.verify(GUEST_ID).unwrap();
}
