use borsh::{BorshDeserialize, BorshSerialize};

/// Data written to DA and read from DA must be the borsh serialization of this enum
/// WARNING: This type has to be the exact same as the one used in citrea repo, so that the borsh serializations are the same.
/// citrea/crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs
#[derive(Debug, Clone, Eq, PartialEq, BorshDeserialize, BorshSerialize)]
#[allow(clippy::large_enum_variant)]
pub(crate) enum DataOnDa {
    /// A zk proof and state diff
    Complete(Proof),
    /// A list of tx ids
    Aggregate(Vec<[u8; 32]>, Vec<[u8; 32]>),
    /// A chunk of an aggregate
    Chunk(Vec<u8>),
    /// A new batch proof method_id
    BatchProofMethodId(BatchProofMethodId),
    /// Sequencer commitment
    SequencerCommitment(SequencerCommitment),
}

/// Commitments made to the DA layer from the sequencer.
/// Has merkle root of l2 block hashes from L1 start block to L1 end block (inclusive)
#[derive(Debug, Clone, Eq, PartialEq, BorshDeserialize, BorshSerialize)]
pub(crate) struct SequencerCommitment {
    /// Merkle root of l2 block hashes
    pub merkle_root: [u8; 32],
    /// Absolute order of the sequencer commitment, the first commitment has index 0, the next one has 1...
    pub index: u32,
    /// End L2 block's number
    pub l2_end_block_number: u64,
}

/// The ZK proof generated by the [`ZkvmHost::run`] method.
type Proof = Vec<u8>;

/// Minimum number of verified signatures required to approve a method id upgrade.
const SECURITY_COUNCIL_SIGNATURE_THRESHOLD: usize = 3;
/// Size of a signature in bytes.
const SECURITY_COUNCIL_SIGNATURE_SIZE: usize = 64;

/// A new batch proof method_id starting to be applied from the l2_block_number (inclusive).
#[derive(Debug, Clone, Eq, PartialEq, BorshSerialize, BorshDeserialize)]
pub(crate) struct BatchProofMethodId {
    /// Body of the method id update, the message to be signed
    /// Includes method id and activation height
    pub body: BatchProofMethodIdBody,
    /// Signatures to be verified for the method id update used for a 3 of 5 security council
    /// Consists of 64 byte keccak256(eip191 prefixed message) prehash signed signatures
    /// The public keys can be recovered from the signatures and the prehash
    /// The indices point to the pubkeys in the light client circuit initial values
    /// To verify the signature the pubkey should be fetched from the initial values corresponding to the signature
    /// If one signature verification fails the whole method id update is invalid
    /// Also assumes the indexes are in ascending order and there are no duplicates
    pub signatures_with_index:
        [([u8; SECURITY_COUNCIL_SIGNATURE_SIZE], u8); SECURITY_COUNCIL_SIGNATURE_THRESHOLD],
}

/// Body of the batch proof method id update for light client
#[derive(Debug, Clone, Eq, PartialEq, BorshDeserialize, BorshSerialize)]
pub(crate) struct BatchProofMethodIdBody {
    /// New method id of upcoming fork
    pub method_id: [u32; 8],
    /// Activation L2 height of the new method id
    pub activation_l2_height: u64,
    /// Network identifier to prevent cross network replay attacks
    pub chain_id: u64,
}
