name: Debug Build Unit and Integration Tests
description: "Runs unit and integration tests for debug builds"

# inputs:
#   github_token:
#     description: "GitHub token for authentication"
#     required: true

runs:
  using: "composite"

  steps:
    - name: Create test log directories
      shell: bash
      run: mkdir -p test-logs/debug

    - name: Save/restore build artifacts
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ runner.os }}-cargo-DEBUG-${{ hashFiles('**/Cargo.lock') }}-${{ github.sha }}

    - name: Run unit tests
      shell: bash
      run: cargo test_unit
    - name: Run integration tests
      shell: bash
      run: cargo test_integration
