name: Build And Test

on:
  push:
    branches:
      - main
      - "releases/*"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ (github.ref != 'refs/heads/main') }}

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: warn,risc0_zkvm=error,risc0_circuit_rv32im=error
  RISC0_DEV_MODE: 1
  RUST_MIN_STACK: 33554432
  PARTIAL_SIG_VERIFICATION: 1

  BITVM_CACHE_PATH: bitvm_cache_dev.bin
  CARGOFLAGS: --workspace --all-targets
  CARGOFLAGS_ALL_FEATURES: --workspace --all-targets --all-features

jobs:
  # Build ----------------------------------------------------------------------
  release_build_all_features:
    name: Release | All features | Compile
    runs-on: ubicloud-standard-16
    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-prerequisites

      - name: Save/restore build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: "false"
          key: "release-all-features"

      - name: Compile in release mode
        run: cargo build $CARGOFLAGS_ALL_FEATURES --release

  release_build:
    name: Release | No features | Compile and Test
    permissions:
      contents: read
    runs-on: ubicloud-standard-4
    if: ${{ !github.event.pull_request.draft }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: clementine
          POSTGRES_USER: clementine
          POSTGRES_PASSWORD: clementine
          POSTGRES_INITDB_ARGS: "-c shared_buffers=8GB -c max_connections=5000"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-prerequisites
      - uses: ./.github/actions/test-prerequisites

      - name: Save/restore build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: "false"
          key: "release-no-automation"

      - name: Compile in release mode
        run: cargo build $CARGOFLAGS --release

      - name: Run no-automation tests # only one test for now
        env:
          LOG_FORMAT: json
          RUST_LOG: info,ci=debug,risc0_zkvm=error,risc0_circuit_rv32im=error
        run: |
          set -o pipefail
          ./scripts/generate_certs.sh
          cargo test --release mock_citrea_run_truthful_manual_reimbursement 2>&1 | tee no_automation_test_output.log

      - name: Upload test artifacts
        if: failure()
        uses: ./.github/actions/test-artifacts
        with:
          artifact_name: release-no-automation-test-logs
          log_dir: test-logs/release
          cargo_output_logs: no_automation_test_output.log

  # Full Tests -----------------------------------------------------------------
  debug_build_test_all_features:
    name: Debug | All features | Test
    runs-on: ubicloud-standard-16

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: clementine
          POSTGRES_USER: clementine
          POSTGRES_PASSWORD: clementine
          POSTGRES_INITDB_ARGS: "-c shared_buffers=8GB -c max_connections=5000"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-prerequisites
      - uses: ./.github/actions/test-prerequisites

      - name: Save/restore build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: "false"
          key: "debug-all-features"

      - name: Run unit tests
        id: unit_tests
        env:
          LOG_FORMAT: json
          RUST_LOG: info,ci=debug,risc0_zkvm=error,risc0_circuit_rv32im=error
        run: |
          set -o pipefail
          ./scripts/generate_certs.sh
          cargo test_unit_debug 2>&1 | tee unit_test_output.log

      - name: Generate and upload deposit state artifact
        if: failure()
        uses: ./.github/actions/deposit-state-artifact
        with:
          profile: debug

      - name: Run integration tests
        env:
          LOG_FORMAT: json
          RUST_LOG: info,ci=debug,risc0_zkvm=error,risc0_circuit_rv32im=error
        run: |
          set -o pipefail
          cargo test_integration 2>&1 | tee integration_test_output.log

      - name: Upload test artifacts
        if: failure()
        uses: ./.github/actions/test-artifacts
        with:
          artifact_name: debug-test-logs
          log_dir: test-logs/debug
          cargo_output_logs: unit_test_output.log integration_test_output.log

  release_build_test_all_features:
    name: Release | All features | Test
    runs-on: ubicloud-standard-16
    if: ${{ !github.event.pull_request.draft }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: clementine
          POSTGRES_USER: clementine
          POSTGRES_PASSWORD: clementine
          POSTGRES_INITDB_ARGS: "-c shared_buffers=8GB -c max_connections=5000"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-prerequisites
      - uses: ./.github/actions/test-prerequisites

      - name: Save/restore build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: "false"
          key: "release-all-features"

      - name: Run unit tests
        id: unit_tests
        env:
          LOG_FORMAT: json
          RUST_LOG: info,ci=debug,risc0_zkvm=error,risc0_circuit_rv32im=error
        run: |
          set -o pipefail
          ./scripts/generate_certs.sh
          cargo test_unit_release 2>&1 | tee unit_test_output.log

      - name: Generate and upload deposit state artifact
        if: failure()
        uses: ./.github/actions/deposit-state-artifact
        with:
          profile: release

      - name: Run integration tests
        env:
          LOG_FORMAT: json
          RUST_LOG: info,ci=debug,risc0_zkvm=error,risc0_circuit_rv32im=error
        run: |
          set -o pipefail
          cargo test_integration_release 2>&1 | tee integration_test_output.log

      - name: Upload test artifacts
        if: failure()
        uses: ./.github/actions/test-artifacts
        with:
          artifact_name: release-test-logs
          log_dir: test-logs/release
          cargo_output_logs: unit_test_output.log integration_test_output.log

  # Matrix (Standalone) Tests --------------------------------------------------
  standalone_tests:
    name: Release | All features | Test ${{ matrix.description_suffix }}
    runs-on: ubicloud-standard-8
    if: ${{ !github.event.pull_request.draft }}

    env:
      INFO_LOG_FILE: ${{ github.workspace }}/test-logs/standalone/standalone-${{ matrix.test_name }}-test.log

    strategy:
      fail-fast: false
      matrix:
        include:
          - test_script_name: additional_disprove_script_test_disrupted_payout_tx_block_hash
            description_suffix: "Add. disprove disrupted payout tx blockhash path"
            test_name: "additional-disrupted-payout"
          - test_script_name: additional_disprove_script_test_disrupt_chal_sending_wts
            description_suffix: "Add. disprove disrupted challenge sending watchtowers path"
            test_name: "additional-disrupted-chal-sending-wts"
          - test_script_name: additional_disprove_script_test_operator_forgot_wt_challenge
            description_suffix: "Add. disprove operator forgot watchtower challenge path"
            test_name: "additional-forgot-challenge"
          - test_script_name: additional_disprove_script_test_disrupted_latest_block_hash
            description_suffix: "Add. disprove disrupted latest blockhash path"
            test_name: "additional-disrupted-latest-blockhash"
          - test_script_name: additional_disprove_script_test_corrupted_public_input
            description_suffix: "Add. disprove disrupted public input path"
            test_name: "additional-corrupted-public-input"
          - test_script_name: bitvm_disprove_scripts::disprove_script_test_healthy
            description_suffix: "Disprove healthy path"
            test_name: "disprove-healthy"
          - test_script_name: bitvm_disprove_scripts::disprove_script_test_corrupted_assert
            description_suffix: "Disprove disrupted assert path"
            test_name: "disprove-corrupted-assert"
          - test_script_name: citrea_deposit_and_withdraw_e2e_non_zero_genesis_height
            description_suffix: "E2E non-zero genesis height"
            test_name: "citrea-deposit-and-withdraw-non-zero-genesis-height"

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: clementine
          POSTGRES_USER: clementine
          POSTGRES_PASSWORD: clementine
          POSTGRES_INITDB_ARGS: "-c shared_buffers=8GB -c max_connections=1000"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-prerequisites
      - uses: ./.github/actions/test-prerequisites

      - name: Save/restore build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: "false"
          key: "release-all-features"

      - name: Run tests
        run: |
          ./scripts/generate_certs.sh
          cargo test ${{ matrix.test_script_name }} $CARGOFLAGS_ALL_FEATURES --release -- --ignored --nocapture

      - name: Upload test artifacts
        if: failure() || cancelled()
        uses: ./.github/actions/test-artifacts
        with:
          artifact_name: standalone-test-logs-${{ matrix.test_name }}
          log_dir: test-logs/standalone
          dump: all
